# Generated by Django 3.0.2 on 2020-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginModel',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('OTP', models.IntegerField(default=1234)),
            ],
        ),
    ]
