# Generated by Django 3.0.2 on 2020-10-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwn', '0002_adminloginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='city_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwn.StateModel'),
        ),
    ]
